stages:
- build

build_main:
  stage: build
  script:
    - git clone https://gitlab.com/g76r/libqtpf.git
    - cd libqtpf && qmake && make
    - git clone https://gitlab.com/g76r/libp6core.git
    - cd libqtssu && qmake && make
    - qmake INCLUDEPATH+=libqtpf INCLUDEPATH+=libqtssu
    - make
  tags:
    - qt
    - c++
